# Generated by Django 3.1.2 on 2020-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('status', models.CharField(choices=[('d', 'Deals'), ('j', 'Jobs')], max_length=1)),
            ],
        ),
    ]
