# Generated by Django 3.1.2 on 2020-10-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Name of the sender', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
